apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnginx3
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
       
    spec:
      containers:
      - name: testnginx3
        image: "melihselamiurkmez/dtcloud:1.1"
        env:
        - name: "PORT"
          value: "80"
          

---
 

apiVersion: v1
kind: Service
metadata:
  name: testnginxlb
spec:
  type: LoadBalancer
  selector:
    app: argocd
  ports:
  - port: 8080
    targetPort: 80





  
 
 
