apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnginx3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
       
    spec:
      containers:
      - name: testnginx3
        image: "melihselamiurkmez/dtcloud:1.1"
        env:
        - name: "PORT"
          value: "80"
          
---

apiVersion: v1
kind: Service
metadata:
  name: testnginx3-svc
spec:
  type: NodePort
  selector:
    app: argocd
    
  ports:
  - name: svc-port
    protocol: TCP
    port: 8080
    targetPort: 80
    

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testnginx3-ingress
  annotations:
    networking.gke.io/managed-certificates: "argocd-nginx"
spec:
  rules:
  - host: dtcloudteam.com
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: testnginx3-svc
            port:
              number: 8080
  
 
 
