apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnginx3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
       
    spec:
      containers:
      - name: hello
        image: "melihselamiurkmez/dtcloud:1.1"
        env:
        - name: "PORT"
          value: "80"
          
---

apiVersion: v1
kind: Service
metadata:
  name: testnginx3-svc
spec:
  type: NodePort
  selector:
    app: argocd
    
  ports:
  - name: svc-port
    protocol: TCP
    port: 8080
    targetPort: 80
    
---

apiVersion: networking.gke.io/v1
  kind: ManagedCertificate
  metadata:
    name: testnginx3
    namespace: argocd
  spec:
    domains:
      - dtcloudteam.com
 
