apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnginx3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: products
        department: sales
    spec:
      containers:
      - name: hello
        image: "melihselamiurkmez/dtcloud:1.1"
        env:
        - name: "PORT"
          value: "443"
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: NodePort
  selector:
    app: argocd
    department: sales
  ports:
  - name: my-first-port
    protocol: TCP
    port: 80
    targetPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svc
spec:
  tls:
  - secretName: secret1
  rules:
  - host: dtcloudintern3.com
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: svc
            port:
              number: 80
