apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnginx3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
       
    spec:
      containers:
      - name: hello
        image: "melihselamiurkmez/dtcloud:1.1"
        env:
        - name: "PORT"
          value: "80"

