apiVersion: apps/v1
kind: Deployment
metadata:
  name: customubuntuimage-deployment
  labels:
    app: ubuntu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image:  europe-west4-docker.pkg.dev/dt-terraform-test/dt-cloud/custom-ubuntu:v2