apiVersion: v1
kind: Service
metadata:
  name: kanboard-service
  namespace: ns-kanboard
spec:
  ports:
  - name: https
    targetPort: 443
    port: 443
    protocol: TCP
  type: NodePort
  selector:
    run: kanboard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kboard-ingress
  namespace: ns-kanboard
spec:
  defaultBackend:
    service:
      name: kanboard-service
      port:
        number: 443
  tls:
  - secretName: kb-secret
