apiVersion: apps/v1
kind: Deployment
metadata:
  name: omer-website
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omer-website1
  template:
    metadata:
      labels:
        app: omer-website1
    spec:
      containers:
      - name: containername
        image: melihselamiurkmez/dtcloud:1.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: omer-test-servis
spec:
  type: NodePort
  selector:
    app: omer-website
  ports:
  - name: my-first-port
    protocol: TCP
    port: 8080
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omer-test-ingress
  namespace: default
spec:
  defaultBackend:
    service:
      name: omer-test-servis
      port:
        number: 8080
  tls:
  - secretName: secret12
