apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtcloudteamnginx3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products
      department: sales
  template:
    metadata:
      labels:
        app: products
        department: sales
    spec:
      containers:
      - name: containername
        image: "melihselamiurkmez/dtcloud:1.1"
        env:
        - name: "PORT"
          value: "50001"
---
apiVersion: v1
kind: Service
metadata:
  name: servis
spec:
  type: NodePort
  selector:
    app: products
    department: sales
  ports:
  - name: my-first-port
    protocol: TCP
    port: 60001
    targetPort: 50001
