apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store-11
  namespace: secretadmin
spec:
  provider:
    gcpsm:
      projectID: dt-terraform-test
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: europe-west1-b
          # name of the GKE cluster
          clusterName: juniors-test-cls
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: dt-terraform-test
          # reference the sa from above
          serviceAccountRef:
            name: eso-ksa
            namespace: secretadmin
