apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-dev
  namespace: secretdev
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store-11             # name of the SecretStore (or kind specified)
  target:
    name: dtcloudsecrettest-k8ssecret  # name of the k8s Secret to be created
    creationPolicy: Owner
  
  data:
  - secretKey: dtcloudsecrettest  # name of the GCPSM secret key
    remoteRef:
      key: dtcloudsecrettest
