apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: gcp-secret-manager-secstr
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: dt-terraform-test
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: europe-west1-b
          # name of the GKE cluster
          clusterName: juniors-test-cls
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: dt-terraform-test
          # reference the sa from above
          serviceAccountRef:
            name: dtcloudsm
