apiVersion: apps/v1
kind: Deployment
metadata:
  name: dt2
spec:
  selector:
    matchLabels:
      app: dt
  template:
    metadata:
      labels:
        app: dt
    spec:
      containers:
      - name: dtcontainer
        image: melihselamiurkmez/dt
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
