apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtcloudteamnginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: webcontainer
        image: melihselamiurkmez/dtcloud:1.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: argocdlbs
spec:
  type: LoadBalancer
  selector:
    app: argocd
  ports:
  - port: 8080
    targetPort: 80
    

